config/routes.rb
Rails.application.routes.draw do

  root 'messages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :questions
  resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  validates :content, presence: true, length: { maximum: 255 }
  belongs_to :question, optional: true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :messages, dependent: :destroy
  validates :title, presence: true, length: { maximum: 50 }
  validates :a_1, presence: true, length: { maximum: 50 }
  validates :a_2, presence: true, length: { maximum: 50 }
  validates :a_3, presence: true, length: { maximum: 50 }
  validates :a_4, presence: true, length: { maximum: 50 }
  validates :answer, presence: true, inclusion: { in: [*1..4] }
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
            uniqueness: { case_sensitive: false }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def index
    @messages = Message.all.order(created_at: :asc)
    @message = Message.new
  end

  def create
    @messages = Message.all.order(created_at: :asc)
    @message_count = @messages.count
    if params[:question_id]
      @question = Question.find(params[:question_id])
      answer = answer_select(@question, params[:answer])
      @message_user = Message.create!(content: answer)
      @message = Message.new(content: "<p>あなたの答えは<span class='text-success'><strong>#{answer}</strong></span>です。</p>", answer: params[:answer], question_id: @question.id, robo: true)
    else
      @message = Message.new(message_params)
    end
    if @message.save && @message.content == "quiz"
      Message.where(finished: false, robo: true, content: "クイズです！！").update_all(finished: true)
      @message_robo = Message.create!(content: 'クイズです！！',question_id: Question.pluck(:id).sample, robo: true)
      render :create
    elsif @message.save && params[:message_id].present?
      puts @message.inspect
      @message_finished = Message.find(params[:message_id])
      @message_finished.update!(finished: true)
      render :create
    elsif @message.save
      render :create
    else
      render :index
    end
  end

  private

  def message_params
    params.require(:message).permit(:content)
  end

  def answer_select(question, answer)
    if answer.to_i == 1
      question.a_1
    elsif answer.to_i == 2
      question.a_2
    elsif answer.to_i == 3
      question.a_3
    elsif answer.to_i == 4
      question.a_4
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user_logged_in, except: [:show, :index]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    begin
      @question.destroy
      respond_to do |format|
        format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
        format.json { head :no_content }
      end
    rescue
      redirect_to questions_path, notice: '使用されたクイズは消せません'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:title, :a_1, :a_2, :a_3, :a_4, :answer)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to root_url
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
  def answer_select(question)
    answer = question.answer
    if answer == 1
      question.a_1
    elsif answer == 2
      question.a_2
    elsif answer == 3
      question.a_3
    elsif answer == 4
      question.a_4
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav class="navbar navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <!-- ハンバーガーボタン -->
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <!-- /ハンバーガーボタン -->
        <!-- ロゴ -->
        <a class="navbar-brand" href="/"><h1>Quiz</h1></a>
        <!-- /ロゴ -->
        <!-- 開閉メニュー -->
        <div class="collapse navbar-collapse" id="navbar-collapse">
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
              <li><%= link_to 'クイズ登録', new_question_path %></li>
              <li><%= link_to 'クイズ一覧', questions_path %></li>
              <li><%= link_to 'ログアウト', logout_path, method: :delete %></li>
            <%# <% else %> %>
              <%# <li><%= link_to '管理者ログイン', login_path %> %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
      <!-- /開閉メニュー -->
  </nav>
</header>
<!-- /header -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <title>Quiz</title>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>

<body>
  <!-- wrapper -->
  <div class="wrapper">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash_messages' %>
    <%= notice %>

    <%= yield %>
  </div>
</body>
</html>

app/views/messages/_form.html.erb
<%= form_with(model: message) do |f| %>
  <%= render 'layouts/error_messages', model: f.object %>
  <div class="form-group row">
    <div class="col-xs-9">
      <%= f.text_field :content, class: 'form-control', placeholder: 'クイズを始めるには、 quiz と入力して下さい' %>
    </div>
    <div class="col-xs-3">
      <%= f.submit "送信", class: 'btn btn-success btn-block', id: 'submit_button' %>
    </div>
  </div>
<% end %>

app/views/messages/_message.html.erb
<% if message.robo == true %>
  <div class="robo-comment comment">
    <div class="icon-chat"></div>
    <div class="message" id="message-<%= message.id %>">

      <%== message.content %>
      <%= render 'questions/question', question: message.question, message: message if !message.answer && message.question_id  %>
      <%= render 'questions/show', question: message.question, message: message if message.answer && message.question_id %>

    </div>
  </div>
<% else %>
  <div class="my-comment comment text-right">
    <div class="message" id="message-<%= message.id %>">
      <p>
        <%= message.content %>
        <%= render 'questions/question', question: message.question, message: message if !message.answer && message.question_id  %>
        <%= render 'questions/show', question: message.question, message: message if message.answer && message.question_id %>
      </p>
    </div>
  </div>
<% end %>

app/views/messages/create.js.erb
<% if @message_finished %>
  $('.robo-comment.comment:last').remove();
  $('.main .container-fluid').append('<%=j render 'messages/message', message: @message_finished %>');
  $('.main .container-fluid').append('<%=j render 'messages/message', message: @message_user %>');
<% end %>
<% if @message_count != 0 %>
  $('#message-<%= @message.id - 1 %>').parent().html('<%=j render 'messages/message', message: Message.find(@message.id - 1) %>');
<% end %>
  $('.main .container-fluid').append('<%=j render 'messages/message', message: @message %>');
<% if @message_robo %>
  $('.main .container-fluid').append('<%=j render 'messages/message', message: @message_robo %>');
<% end %>
$('#message_content').val('');
footerStart("#item");

app/views/messages/index.html.erb
<div id="parent">
  <div class="main">
    <div class="container-fluid">
      <%= render @messages %>
    </div>
  </div>

  <footer class="footer">
    <div class="container-fluid">
      <%= render 'form', message: @message %>
    </div>
  </footer>
</div>

<script>
  function footerStart(selector){
    $('html').animate({scrollTop: $(selector).offset().top}, 500);
  }

  $("#parent").append("<div id='item'></div>");
  footerStart("#item");
</script>

app/views/questions/_form.html.erb
<div class="row">
  <div class="col-xs-12">
    <%= form_with(model: question, local: true) do |form| %>
      <%= render 'layouts/error_messages', model: form.object %>

      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :a_1 %>
        <%= form.text_field :a_1, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :a_2 %>
        <%= form.text_field :a_2, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :a_3 %>
        <%= form.text_field :a_3, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :a_4 %>
        <%= form.text_field :a_4, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :answer %>
        <%= form.select :answer, { a_1: 1, a_2: 2, a_3: 3, a_4: 4 }, {}, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.submit '投稿する', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/questions/_question.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= question.title %>
  </div>
  <% if !message.finished %>
    <div class="list-group">
      <%= link_to( question.a_1, messages_path(question_id: question.id, answer: 1, message_id: message.id), method: :post, class: 'list-group-item', remote: true) %>
      <%= link_to( question.a_2, messages_path(question_id: question.id, answer: 2, message_id: message.id), method: :post, class: 'list-group-item', remote: true) %>
      <%= link_to( question.a_3, messages_path(question_id: question.id, answer: 3, message_id: message.id), method: :post, class: 'list-group-item', remote: true) %>
      <%= link_to( question.a_4, messages_path(question_id: question.id, answer: 4, message_id: message.id), method: :post, class: 'list-group-item', remote: true) %>
    </div>
    <% if logged_in?  %>
      <div class="comment-menu panel-body text-right">
        <%= link_to '変更', edit_question_path(question) %>
        <%= link_to '消去', question, method: :delete, data: { confirm: 'ほんとうに削除しますか？' } %>
      </div>
    <% end %>
  <% else %>
    <div class="panel-body">
     <p>回答済みのクイズです</p>
      <% if logged_in?  %>
        <div class="comment-menu text-right">
          <%= link_to '変更', edit_question_path(question) %>
          <%= link_to '消去', question, method: :delete, data: { confirm: 'ほんとうに削除しますか？' } %>
        </div>
      <% end %>
    </div>
  <% end %>



</div>

app/views/questions/_show.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <%= question.title %>
  </div>
  <ul class="list-group">
    <li class="list-group-item a_1_<%= message.id %>"><%= question.a_1 %></li>
    <li class="list-group-item a_2_<%= message.id %>"><%= question.a_2 %></li>
    <li class="list-group-item a_3_<%= message.id %>"><%= question.a_3 %></li>
    <li class="list-group-item a_4_<%= message.id %>"><%= question.a_4 %></li>
  </ul>
  <div class="panel-footer">

    <% if message.answer == question.answer %>
      <p class="text-danger"><i class="icon-circle"></i> 正解</p>
      <p>正解！！答えは<%= answer_select(question) %>です。</p>
    <% else %>
      <p class="text-info"><i class="glyphicon glyphicon-remove"></i> 残念</p>
      <p>残念・・・答えは<%= answer_select(question) %>でした。</p>
    <% end %>
  </div>
</div>

<script>
  console.log('.a_<%= question.answer %>_<%= message.id %>');
  $('.a_<%= question.answer %>_<%= message.id %>').addClass('list-group-item-danger');
  if ('<%= message.answer.to_s %>' != '<%= question.answer.to_s %>') {
    $('.a_<%= message.answer %>_<%= message.id %>').addClass('list-group-item-info');
  }
</script>

app/views/questions/edit.html.erb
<div id="admin">
  <h1>Editing Question</h1>

  <%= render 'form', question: @question %>

  <%= link_to 'Show', @question %> |
  <%= link_to 'Back', questions_path %>
</div>

app/views/questions/index.html.erb
<div id="admin">
  <h1>Questions</h1>

      <% @questions.each do |question| %>
        <div class="panel panel-default">
          <div class="panel-heading"><%= question.title %></div>

          <div class="panel-body">
            <div class="badge">
              <%= question.a_1 %>
            </div>
            <div class="badge">
              <%= question.a_2 %>
            </div>
            <div class="badge">
              <%= question.a_3 %>
            </div>
            <div class="badge">
              <%= question.a_4 %>
            </div>
            <% if logged_in? %>
              <%= link_to 'Edit', edit_question_path(question) %> |
              <%= link_to 'Destroy', question, method: :delete, data: { confirm: '消去してもよろしいですか？' } %>
            <% end %>
          </div>
        </div>
      <% end %>


  <br>

  <%= link_to 'New Question', new_question_path if logged_in? %>
</div>

app/views/questions/new.html.erb
<div id="admin">
  <h1>New Question</h1>

  <%= render 'form', question: @question %>

  <%= link_to 'Back', questions_path %>
</div>

app/views/questions/show.html.erb
<div id="admin">
  <h1><%= @question.title %></h1>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-defaulte show_panel a_1">
        <div class="panel-body"><p><%= @question.a_1 %></p></div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-defaulte show_panel a_2">
        <div class="panel-body"><p><%= @question.a_2 %></p></div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-defaulte show_panel a_3">
        <div class="panel-body"><p><%= @question.a_3 %></p></div>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="panel panel-defaulte show_panel a_4">
        <div class="panel-body"><p><%= @question.a_4 %></p></div>
      </div>
    </div>
  </div>


  <%= link_to 'Edit', edit_question_path(@question) %> |
  <%= link_to 'Top', root_path %>
</div>